version: '3'
services:
  app:
    image: golang:alpine
    container_name: go-db-starter
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/go/src/go-db-starter
    working_dir: /go/src/go-db-starter
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=v4wedsavhoqwd
      - MARIADB_DB=golangstarter
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - 'gofiber-net'
    command: sh -c "go run *.go"
  db:
    image: mariadb
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=g240iowejgadvsijfgwrgafd
      - MYSQL_DATABASE=golangstarter
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=v4wedsavhoqwd
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - 'gofiber-net'
networks:
  gofiber-net:
    name: gofiber-net

